const countryList = [
  {
    es: 'Afganistán',
    en: 'Afghanistan',
    fr: 'Afghanistan',
    code: 'AF',
    code3: 'AFG',
    phonePrefix: 93,
  },
  {
    es: 'Albania',
    en: 'Albania',
    fr: 'Albanie',
    code: 'AL',
    code3: 'ALB',
    phonePrefix: 355,
  },
  {
    es: 'Alemania',
    en: 'Germany',
    fr: 'Allemagne',
    code: 'DE',
    code3: 'DEU',
    phonePrefix: 49,
  },
  {
    es: 'Andorra',
    en: 'Andorra',
    fr: 'Andorra',
    code: 'AD',
    code3: 'AND',
    phonePrefix: 376,
  },
  {
    es: 'Angola',
    en: 'Angola',
    fr: 'Angola',
    code: 'AO',
    code3: 'AGO',
    phonePrefix: 244,
  },
  {
    es: 'Anguila',
    en: 'Anguilla',
    fr: 'Anguilla',
    code: 'AI',
    code3: 'AIA',
    phonePrefix: '1 264',
  },
  {
    es: 'Antártida',
    en: 'Antarctica',
    fr: "L'Antarctique",
    code: 'AQ',
    code3: 'ATA',
    phonePrefix: 672,
  },
  {
    es: 'Antigua y Barbuda',
    en: 'Antigua and Barbuda',
    fr: 'Antigua et Barbuda',
    code: 'AG',
    code3: 'ATG',
    phonePrefix: '1 268',
  },
  {
    es: 'Arabia Saudita',
    en: 'Saudi Arabia',
    fr: 'Arabie Saoudite',
    code: 'SA',
    code3: 'SAU',
    phonePrefix: 966,
  },
  {
    es: 'Argelia',
    en: 'Algeria',
    fr: 'Algérie',
    code: 'DZ',
    code3: 'DZA',
    phonePrefix: 213,
  },
  {
    es: 'Argentina',
    en: 'Argentina',
    fr: 'Argentine',
    code: 'AR',
    code3: 'ARG',
    phonePrefix: 54,
  },
  {
    es: 'Armenia',
    en: 'Armenia',
    fr: "L'Arménie",
    code: 'AM',
    code3: 'ARM',
    phonePrefix: 374,
  },
  {
    es: 'Aruba',
    en: 'Aruba',
    fr: 'Aruba',
    code: 'AW',
    code3: 'ABW',
    phonePrefix: 297,
  },
  {
    es: 'Australia',
    en: 'Australia',
    fr: 'Australie',
    code: 'AU',
    code3: 'AUS',
    phonePrefix: 61,
  },
  {
    es: 'Austria',
    en: 'Austria',
    fr: 'Autriche',
    code: 'AT',
    code3: 'AUT',
    phonePrefix: 43,
  },
  {
    es: 'Azerbaiyán',
    en: 'Azerbaijan',
    fr: "L'Azerbaïdjan",
    code: 'AZ',
    code3: 'AZE',
    phonePrefix: 994,
  },
  {
    es: 'Bélgica',
    en: 'Belgium',
    fr: 'Belgique',
    code: 'BE',
    code3: 'BEL',
    phonePrefix: 32,
  },
  {
    es: 'Bahamas',
    en: 'Bahamas',
    fr: 'Bahamas',
    code: 'BS',
    code3: 'BHS',
    phonePrefix: '1 242',
  },
  {
    es: 'Bahrein',
    en: 'Bahrain',
    fr: 'Bahreïn',
    code: 'BH',
    code3: 'BHR',
    phonePrefix: 973,
  },
  {
    es: 'Bangladesh',
    en: 'Bangladesh',
    fr: 'Bangladesh',
    code: 'BD',
    code3: 'BGD',
    phonePrefix: 880,
  },
  {
    es: 'Barbados',
    en: 'Barbados',
    fr: 'Barbade',
    code: 'BB',
    code3: 'BRB',
    phonePrefix: '1 246',
  },
  {
    es: 'Belice',
    en: 'Belize',
    fr: 'Belize',
    code: 'BZ',
    code3: 'BLZ',
    phonePrefix: 501,
  },
  {
    es: 'Benín',
    en: 'Benin',
    fr: 'Bénin',
    code: 'BJ',
    code3: 'BEN',
    phonePrefix: 229,
  },
  {
    es: 'Bhután',
    en: 'Bhutan',
    fr: 'Le Bhoutan',
    code: 'BT',
    code3: 'BTN',
    phonePrefix: 975,
  },
  {
    es: 'Bielorrusia',
    en: 'Belarus',
    fr: 'Biélorussie',
    code: 'BY',
    code3: 'BLR',
    phonePrefix: 375,
  },
  {
    es: 'Birmania',
    en: 'Myanmar',
    fr: 'Myanmar',
    code: 'MM',
    code3: 'MMR',
    phonePrefix: 95,
  },
  {
    es: 'Bolivia',
    en: 'Bolivia',
    fr: 'Bolivie',
    code: 'BO',
    code3: 'BOL',
    phonePrefix: 591,
  },
  {
    es: 'Bosnia y Herzegovina',
    en: 'Bosnia and Herzegovina',
    fr: 'Bosnie-Herzégovine',
    code: 'BA',
    code3: 'BIH',
    phonePrefix: 387,
  },
  {
    es: 'Botsuana',
    en: 'Botswana',
    fr: 'Botswana',
    code: 'BW',
    code3: 'BWA',
    phonePrefix: 267,
  },
  {
    es: 'Brasil',
    en: 'Brazil',
    fr: 'Brésil',
    code: 'BR',
    code3: 'BRA',
    phonePrefix: 55,
  },
  {
    es: 'Brunéi',
    en: 'Brunei',
    fr: 'Brunei',
    code: 'BN',
    code3: 'BRN',
    phonePrefix: 673,
  },
  {
    es: 'Bulgaria',
    en: 'Bulgaria',
    fr: 'Bulgarie',
    code: 'BG',
    code3: 'BGR',
    phonePrefix: 359,
  },
  {
    es: 'Burkina Faso',
    en: 'Burkina Faso',
    fr: 'Burkina Faso',
    code: 'BF',
    code3: 'BFA',
    phonePrefix: 226,
  },
  {
    es: 'Burundi',
    en: 'Burundi',
    fr: 'Burundi',
    code: 'BI',
    code3: 'BDI',
    phonePrefix: 257,
  },
  {
    es: 'Cabo Verde',
    en: 'Cape Verde',
    fr: 'Cap-Vert',
    code: 'CV',
    code3: 'CPV',
    phonePrefix: 238,
  },
  {
    es: 'Camboya',
    en: 'Cambodia',
    fr: 'Cambodge',
    code: 'KH',
    code3: 'KHM',
    phonePrefix: 855,
  },
  {
    es: 'Camerún',
    en: 'Cameroon',
    fr: 'Cameroun',
    code: 'CM',
    code3: 'CMR',
    phonePrefix: 237,
  },
  {
    es: 'Canadá',
    en: 'Canada',
    fr: 'Canada',
    code: 'CA',
    code3: 'CAN',
    phonePrefix: 1,
  },
  {
    es: 'Chad',
    en: 'Chad',
    fr: 'Tchad',
    code: 'TD',
    code3: 'TCD',
    phonePrefix: 235,
  },
  {
    es: 'Chile',
    en: 'Chile',
    fr: 'Chili',
    code: 'CL',
    code3: 'CHL',
    phonePrefix: 56,
  },
  {
    es: 'China',
    en: 'China',
    fr: 'Chine',
    code: 'CN',
    code3: 'CHN',
    phonePrefix: 86,
  },
  {
    es: 'Chipre',
    en: 'Cyprus',
    fr: 'Chypre',
    code: 'CY',
    code3: 'CYP',
    phonePrefix: 357,
  },
  {
    es: 'Ciudad del Vaticano',
    en: 'Vatican City State',
    fr: 'Cité du Vatican',
    code: 'VA',
    code3: 'VAT',
    phonePrefix: 39,
  },
  {
    es: 'Colombia',
    en: 'Colombia',
    fr: 'Colombie',
    code: 'CO',
    code3: 'COL',
    phonePrefix: 57,
  },
  {
    es: 'Comoras',
    en: 'Comoros',
    fr: 'Comores',
    code: 'KM',
    code3: 'COM',
    phonePrefix: 269,
  },
  {
    es: 'República del Congo',
    en: 'Republic of the Congo',
    fr: 'République du Congo',
    code: 'CG',
    code3: 'COG',
    phonePrefix: 242,
  },
  {
    es: 'República Democrática del Congo',
    en: 'Democratic Republic of the Congo',
    fr: 'République démocratique du Congo',
    code: 'CD',
    code3: 'COD',
    phonePrefix: 243,
  },
  {
    es: 'Corea del Norte',
    en: 'North Korea',
    fr: 'Corée du Nord',
    code: 'KP',
    code3: 'PRK',
    phonePrefix: 850,
  },
  {
    es: 'Corea del Sur',
    en: 'South Korea',
    fr: 'Corée du Sud',
    code: 'KR',
    code3: 'KOR',
    phonePrefix: 82,
  },
  {
    es: 'Costa de Marfil',
    en: 'Ivory Coast',
    fr: "Côte-d'Ivoire",
    code: 'CI',
    code3: 'CIV',
    phonePrefix: 225,
  },
  {
    es: 'Costa Rica',
    en: 'Costa Rica',
    fr: 'Costa Rica',
    code: 'CR',
    code3: 'CRI',
    phonePrefix: 506,
  },
  {
    es: 'Croacia',
    en: 'Croatia',
    fr: 'Croatie',
    code: 'HR',
    code3: 'HRV',
    phonePrefix: 385,
  },
  {
    es: 'Cuba',
    en: 'Cuba',
    fr: 'Cuba',
    code: 'CU',
    code3: 'CUB',
    phonePrefix: 53,
  },
  {
    es: 'Curazao',
    en: 'Curaçao',
    fr: 'Curaçao',
    code: 'CW',
    code3: 'CWU',
    phonePrefix: 5999,
  },
  {
    es: 'Dinamarca',
    en: 'Denmark',
    fr: 'Danemark',
    code: 'DK',
    code3: 'DNK',
    phonePrefix: 45,
  },
  {
    es: 'Dominica',
    en: 'Dominica',
    fr: 'Dominique',
    code: 'DM',
    code3: 'DMA',
    phonePrefix: '1 767',
  },
  {
    es: 'Ecuador',
    en: 'Ecuador',
    fr: 'Equateur',
    code: 'EC',
    code3: 'ECU',
    phonePrefix: 593,
  },
  {
    es: 'Egipto',
    en: 'Egypt',
    fr: 'Egypte',
    code: 'EG',
    code3: 'EGY',
    phonePrefix: 20,
  },
  {
    es: 'El Salvador',
    en: 'El Salvador',
    fr: 'El Salvador',
    code: 'SV',
    code3: 'SLV',
    phonePrefix: 503,
  },
  {
    es: 'Emiratos Árabes Unidos',
    en: 'United Arab Emirates',
    fr: 'Emirats Arabes Unis',
    code: 'AE',
    code3: 'ARE',
    phonePrefix: 971,
  },
  {
    es: 'Eritrea',
    en: 'Eritrea',
    fr: 'Erythrée',
    code: 'ER',
    code3: 'ERI',
    phonePrefix: 291,
  },
  {
    es: 'Eslovaquia',
    en: 'Slovakia',
    fr: 'Slovaquie',
    code: 'SK',
    code3: 'SVK',
    phonePrefix: 421,
  },
  {
    es: 'Eslovenia',
    en: 'Slovenia',
    fr: 'Slovénie',
    code: 'SI',
    code3: 'SVN',
    phonePrefix: 386,
  },
  {
    es: 'España',
    en: 'Spain',
    fr: 'Espagne',
    code: 'ES',
    code3: 'ESP',
    phonePrefix: 34,
  },
  {
    es: 'Estados Unidos de América',
    en: 'United States of America',
    fr: "États-Unis d'Amérique",
    code: 'US',
    code3: 'USA',
    phonePrefix: 1,
  },
  {
    es: 'Estonia',
    en: 'Estonia',
    fr: "L'Estonie",
    code: 'EE',
    code3: 'EST',
    phonePrefix: 372,
  },
  {
    es: 'Etiopía',
    en: 'Ethiopia',
    fr: 'Ethiopie',
    code: 'ET',
    code3: 'ETH',
    phonePrefix: 251,
  },
  {
    es: 'Filipinas',
    en: 'Philippines',
    fr: 'Philippines',
    code: 'PH',
    code3: 'PHL',
    phonePrefix: 63,
  },
  {
    es: 'Finlandia',
    en: 'Finland',
    fr: 'Finlande',
    code: 'FI',
    code3: 'FIN',
    phonePrefix: 358,
  },
  {
    es: 'Fiyi',
    en: 'Fiji',
    fr: 'Fidji',
    code: 'FJ',
    code3: 'FJI',
    phonePrefix: 679,
  },
  {
    es: 'Francia',
    en: 'France',
    fr: 'France',
    code: 'FR',
    code3: 'FRA',
    phonePrefix: 33,
  },
  {
    es: 'Gabón',
    en: 'Gabon',
    fr: 'Gabon',
    code: 'GA',
    code3: 'GAB',
    phonePrefix: 241,
  },
  {
    es: 'Gambia',
    en: 'Gambia',
    fr: 'Gambie',
    code: 'GM',
    code3: 'GMB',
    phonePrefix: 220,
  },
  {
    es: 'Georgia',
    en: 'Georgia',
    fr: 'Géorgie',
    code: 'GE',
    code3: 'GEO',
    phonePrefix: 995,
  },
  {
    es: 'Ghana',
    en: 'Ghana',
    fr: 'Ghana',
    code: 'GH',
    code3: 'GHA',
    phonePrefix: 233,
  },
  {
    es: 'Gibraltar',
    en: 'Gibraltar',
    fr: 'Gibraltar',
    code: 'GI',
    code3: 'GIB',
    phonePrefix: 350,
  },
  {
    es: 'Granada',
    en: 'Grenada',
    fr: 'Grenade',
    code: 'GD',
    code3: 'GRD',
    phonePrefix: '1 473',
  },
  {
    es: 'Grecia',
    en: 'Greece',
    fr: 'Grèce',
    code: 'GR',
    code3: 'GRC',
    phonePrefix: 30,
  },
  {
    es: 'Groenlandia',
    en: 'Greenland',
    fr: 'Groenland',
    code: 'GL',
    code3: 'GRL',
    phonePrefix: 299,
  },
  {
    es: 'Guadalupe',
    en: 'Guadeloupe',
    fr: 'Guadeloupe',
    code: 'GP',
    code3: 'GLP',
    phonePrefix: 590,
  },
  {
    es: 'Guam',
    en: 'Guam',
    fr: 'Guam',
    code: 'GU',
    code3: 'GUM',
    phonePrefix: '1 671',
  },
  {
    es: 'Guatemala',
    en: 'Guatemala',
    fr: 'Guatemala',
    code: 'GT',
    code3: 'GTM',
    phonePrefix: 502,
  },
  {
    es: 'Guayana Francesa',
    en: 'French Guiana',
    fr: 'Guyane française',
    code: 'GF',
    code3: 'GUF',
    phonePrefix: 594,
  },
  {
    es: 'Guernsey',
    en: 'Guernsey',
    fr: 'Guernesey',
    code: 'GG',
    code3: 'GGY',
    phonePrefix: 44,
  },
  {
    es: 'Guinea',
    en: 'Guinea',
    fr: 'Guinée',
    code: 'GN',
    code3: 'GIN',
    phonePrefix: 224,
  },
  {
    es: 'Guinea Ecuatorial',
    en: 'Equatorial Guinea',
    fr: 'Guinée Equatoriale',
    code: 'GQ',
    code3: 'GNQ',
    phonePrefix: 240,
  },
  {
    es: 'Guinea-Bissau',
    en: 'Guinea-Bissau',
    fr: 'Guinée-Bissau',
    code: 'GW',
    code3: 'GNB',
    phonePrefix: 245,
  },
  {
    es: 'Guyana',
    en: 'Guyana',
    fr: 'Guyane',
    code: 'GY',
    code3: 'GUY',
    phonePrefix: 592,
  },
  {
    es: 'Haití',
    en: 'Haiti',
    fr: 'Haïti',
    code: 'HT',
    code3: 'HTI',
    phonePrefix: 509,
  },
  {
    es: 'Honduras',
    en: 'Honduras',
    fr: 'Honduras',
    code: 'HN',
    code3: 'HND',
    phonePrefix: 504,
  },
  {
    es: 'Hong kong',
    en: 'Hong Kong',
    fr: 'Hong Kong',
    code: 'HK',
    code3: 'HKG',
    phonePrefix: 852,
  },
  {
    es: 'Hungría',
    en: 'Hungary',
    fr: 'Hongrie',
    code: 'HU',
    code3: 'HUN',
    phonePrefix: 36,
  },
  {
    es: 'India',
    en: 'India',
    fr: 'Inde',
    code: 'IN',
    code3: 'IND',
    phonePrefix: 91,
  },
  {
    es: 'Indonesia',
    en: 'Indonesia',
    fr: 'Indonésie',
    code: 'ID',
    code3: 'IDN',
    phonePrefix: 62,
  },
  {
    es: 'Irán',
    en: 'Iran',
    fr: 'Iran',
    code: 'IR',
    code3: 'IRN',
    phonePrefix: 98,
  },
  {
    es: 'Irak',
    en: 'Iraq',
    fr: 'Irak',
    code: 'IQ',
    code3: 'IRQ',
    phonePrefix: 964,
  },
  {
    es: 'Irlanda',
    en: 'Ireland',
    fr: 'Irlande',
    code: 'IE',
    code3: 'IRL',
    phonePrefix: 353,
  },
  {
    es: 'Isla Bouvet',
    en: 'Bouvet Island',
    fr: 'Bouvet Island',
    code: 'BV',
    code3: 'BVT',
    phonePrefix: '',
  },
  {
    es: 'Isla de Man',
    en: 'Isle of Man',
    fr: 'Ile de Man',
    code: 'IM',
    code3: 'IMN',
    phonePrefix: 44,
  },
  {
    es: 'Isla de Navidad',
    en: 'Christmas Island',
    fr: 'Christmas Island',
    code: 'CX',
    code3: 'CXR',
    phonePrefix: 61,
  },
  {
    es: 'Isla Norfolk',
    en: 'Norfolk Island',
    fr: 'Île de Norfolk',
    code: 'NF',
    code3: 'NFK',
    phonePrefix: 672,
  },
  {
    es: 'Islandia',
    en: 'Iceland',
    fr: 'Islande',
    code: 'IS',
    code3: 'ISL',
    phonePrefix: 354,
  },
  {
    es: 'Islas Bermudas',
    en: 'Bermuda Islands',
    fr: 'Bermudes',
    code: 'BM',
    code3: 'BMU',
    phonePrefix: '1 441',
  },
  {
    es: 'Islas Caimán',
    en: 'Cayman Islands',
    fr: 'Iles Caïmans',
    code: 'KY',
    code3: 'CYM',
    phonePrefix: '1 345',
  },
  {
    es: 'Islas Cocos (Keeling)',
    en: 'Cocos (Keeling) Islands',
    fr: 'Cocos (Keeling',
    code: 'CC',
    code3: 'CCK',
    phonePrefix: 61,
  },
  {
    es: 'Islas Cook',
    en: 'Cook Islands',
    fr: 'Iles Cook',
    code: 'CK',
    code3: 'COK',
    phonePrefix: 682,
  },
  {
    es: 'Islas de Åland',
    en: 'Åland Islands',
    fr: 'Îles Åland',
    code: 'AX',
    code3: 'ALA',
    phonePrefix: 358,
  },
  {
    es: 'Islas Feroe',
    en: 'Faroe Islands',
    fr: 'Iles Féro',
    code: 'FO',
    code3: 'FRO',
    phonePrefix: 298,
  },
  {
    es: 'Islas Georgias del Sur y Sandwich del Sur',
    en: 'South Georgia and the South Sandwich Islands',
    fr: 'Géorgie du Sud et les Îles Sandwich du Sud',
    code: 'GS',
    code3: 'SGS',
    phonePrefix: 500,
  },
  {
    es: 'Islas Heard y McDonald',
    en: 'Heard Island and McDonald Islands',
    fr: 'Les îles Heard et McDonald',
    code: 'HM',
    code3: 'HMD',
    phonePrefix: '',
  },
  {
    es: 'Islas Maldivas',
    en: 'Maldives',
    fr: 'Maldives',
    code: 'MV',
    code3: 'MDV',
    phonePrefix: 960,
  },
  {
    es: 'Islas Malvinas',
    en: 'Falkland Islands (Malvinas)',
    fr: 'Iles Falkland (Malvinas',
    code: 'FK',
    code3: 'FLK',
    phonePrefix: 500,
  },
  {
    es: 'Islas Marianas del Norte',
    en: 'Northern Mariana Islands',
    fr: 'Iles Mariannes du Nord',
    code: 'MP',
    code3: 'MNP',
    phonePrefix: '1 670',
  },
  {
    es: 'Islas Marshall',
    en: 'Marshall Islands',
    fr: 'Iles Marshall',
    code: 'MH',
    code3: 'MHL',
    phonePrefix: 692,
  },
  {
    es: 'Islas Pitcairn',
    en: 'Pitcairn Islands',
    fr: 'Iles Pitcairn',
    code: 'PN',
    code3: 'PCN',
    phonePrefix: 870,
  },
  {
    es: 'Islas Salomón',
    en: 'Solomon Islands',
    fr: 'Iles Salomon',
    code: 'SB',
    code3: 'SLB',
    phonePrefix: 677,
  },
  {
    es: 'Islas Turcas y Caicos',
    en: 'Turks and Caicos Islands',
    fr: 'Iles Turques et Caïques',
    code: 'TC',
    code3: 'TCA',
    phonePrefix: '1 649',
  },
  {
    es: 'Islas Ultramarinas Menores de Estados Unidos',
    en: 'United States Minor Outlying Islands',
    fr: 'États-Unis Îles mineures éloignées',
    code: 'UM',
    code3: 'UMI',
    phonePrefix: 246,
  },
  {
    es: 'Islas Vírgenes Británicas',
    en: 'Virgin Islands',
    fr: 'Iles Vierges',
    code: 'VG',
    code3: 'VGB',
    phonePrefix: '1 284',
  },
  {
    es: 'Islas Vírgenes de los Estados Unidos',
    en: 'United States Virgin Islands',
    fr: 'Îles Vierges américaines',
    code: 'VI',
    code3: 'VIR',
    phonePrefix: '1 340',
  },
  {
    es: 'Israel',
    en: 'Israel',
    fr: 'Israël',
    code: 'IL',
    code3: 'ISR',
    phonePrefix: 972,
  },
  {
    es: 'Italia',
    en: 'Italy',
    fr: 'Italie',
    code: 'IT',
    code3: 'ITA',
    phonePrefix: 39,
  },
  {
    es: 'Jamaica',
    en: 'Jamaica',
    fr: 'Jamaïque',
    code: 'JM',
    code3: 'JAM',
    phonePrefix: '1 876',
  },
  {
    es: 'Japón',
    en: 'Japan',
    fr: 'Japon',
    code: 'JP',
    code3: 'JPN',
    phonePrefix: 81,
  },
  {
    es: 'Jersey',
    en: 'Jersey',
    fr: 'Maillot',
    code: 'JE',
    code3: 'JEY',
    phonePrefix: 44,
  },
  {
    es: 'Jordania',
    en: 'Jordan',
    fr: 'Jordan',
    code: 'JO',
    code3: 'JOR',
    phonePrefix: 962,
  },
  {
    es: 'Kazajistán',
    en: 'Kazakhstan',
    fr: 'Le Kazakhstan',
    code: 'KZ',
    code3: 'KAZ',
    phonePrefix: 7,
  },
  {
    es: 'Kenia',
    en: 'Kenya',
    fr: 'Kenya',
    code: 'KE',
    code3: 'KEN',
    phonePrefix: 254,
  },
  {
    es: 'Kirguistán',
    en: 'Kyrgyzstan',
    fr: 'Kirghizstan',
    code: 'KG',
    code3: 'KGZ',
    phonePrefix: 996,
  },
  {
    es: 'Kiribati',
    en: 'Kiribati',
    fr: 'Kiribati',
    code: 'KI',
    code3: 'KIR',
    phonePrefix: 686,
  },
  {
    es: 'Kuwait',
    en: 'Kuwait',
    fr: 'Koweït',
    code: 'KW',
    code3: 'KWT',
    phonePrefix: 965,
  },
  {
    es: 'Líbano',
    en: 'Lebanon',
    fr: 'Liban',
    code: 'LB',
    code3: 'LBN',
    phonePrefix: 961,
  },
  {
    es: 'Laos',
    en: 'Laos',
    fr: 'Laos',
    code: 'LA',
    code3: 'LAO',
    phonePrefix: 856,
  },
  {
    es: 'Lesoto',
    en: 'Lesotho',
    fr: 'Lesotho',
    code: 'LS',
    code3: 'LSO',
    phonePrefix: 266,
  },
  {
    es: 'Letonia',
    en: 'Latvia',
    fr: 'La Lettonie',
    code: 'LV',
    code3: 'LVA',
    phonePrefix: 371,
  },
  {
    es: 'Liberia',
    en: 'Liberia',
    fr: 'Liberia',
    code: 'LR',
    code3: 'LBR',
    phonePrefix: 231,
  },
  {
    es: 'Libia',
    en: 'Libya',
    fr: 'Libye',
    code: 'LY',
    code3: 'LBY',
    phonePrefix: 218,
  },
  {
    es: 'Liechtenstein',
    en: 'Liechtenstein',
    fr: 'Liechtenstein',
    code: 'LI',
    code3: 'LIE',
    phonePrefix: 423,
  },
  {
    es: 'Lituania',
    en: 'Lithuania',
    fr: 'La Lituanie',
    code: 'LT',
    code3: 'LTU',
    phonePrefix: 370,
  },
  {
    es: 'Luxemburgo',
    en: 'Luxembourg',
    fr: 'Luxembourg',
    code: 'LU',
    code3: 'LUX',
    phonePrefix: 352,
  },
  {
    es: 'México',
    en: 'Mexico',
    fr: 'Mexique',
    code: 'MX',
    code3: 'MEX',
    phonePrefix: 52,
  },
  {
    es: 'Mónaco',
    en: 'Monaco',
    fr: 'Monaco',
    code: 'MC',
    code3: 'MCO',
    phonePrefix: 377,
  },
  {
    es: 'Macao',
    en: 'Macao',
    fr: 'Macao',
    code: 'MO',
    code3: 'MAC',
    phonePrefix: 853,
  },
  {
    es: 'Macedônia',
    en: 'Macedonia',
    fr: 'Macédoine',
    code: 'MK',
    code3: 'MKD',
    phonePrefix: 389,
  },
  {
    es: 'Madagascar',
    en: 'Madagascar',
    fr: 'Madagascar',
    code: 'MG',
    code3: 'MDG',
    phonePrefix: 261,
  },
  {
    es: 'Malasia',
    en: 'Malaysia',
    fr: 'Malaisie',
    code: 'MY',
    code3: 'MYS',
    phonePrefix: 60,
  },
  {
    es: 'Malawi',
    en: 'Malawi',
    fr: 'Malawi',
    code: 'MW',
    code3: 'MWI',
    phonePrefix: 265,
  },
  {
    es: 'Mali',
    en: 'Mali',
    fr: 'Mali',
    code: 'ML',
    code3: 'MLI',
    phonePrefix: 223,
  },
  {
    es: 'Malta',
    en: 'Malta',
    fr: 'Malte',
    code: 'MT',
    code3: 'MLT',
    phonePrefix: 356,
  },
  {
    es: 'Marruecos',
    en: 'Morocco',
    fr: 'Maroc',
    code: 'MA',
    code3: 'MAR',
    phonePrefix: 212,
  },
  {
    es: 'Martinica',
    en: 'Martinique',
    fr: 'Martinique',
    code: 'MQ',
    code3: 'MTQ',
    phonePrefix: 596,
  },
  {
    es: 'Mauricio',
    en: 'Mauritius',
    fr: 'Iles Maurice',
    code: 'MU',
    code3: 'MUS',
    phonePrefix: 230,
  },
  {
    es: 'Mauritania',
    en: 'Mauritania',
    fr: 'Mauritanie',
    code: 'MR',
    code3: 'MRT',
    phonePrefix: 222,
  },
  {
    es: 'Mayotte',
    en: 'Mayotte',
    fr: 'Mayotte',
    code: 'YT',
    code3: 'MYT',
    phonePrefix: 262,
  },
  {
    es: 'Micronesia',
    en: 'Estados Federados de',
    fr: 'Federados Estados de',
    code: 'FM',
    code3: 'FSM',
    phonePrefix: 691,
  },
  {
    es: 'Moldavia',
    en: 'Moldova',
    fr: 'Moldavie',
    code: 'MD',
    code3: 'MDA',
    phonePrefix: 373,
  },
  {
    es: 'Mongolia',
    en: 'Mongolia',
    fr: 'Mongolie',
    code: 'MN',
    code3: 'MNG',
    phonePrefix: 976,
  },
  {
    es: 'Montenegro',
    en: 'Montenegro',
    fr: 'Monténégro',
    code: 'ME',
    code3: 'MNE',
    phonePrefix: 382,
  },
  {
    es: 'Montserrat',
    en: 'Montserrat',
    fr: 'Montserrat',
    code: 'MS',
    code3: 'MSR',
    phonePrefix: '1 664',
  },
  {
    es: 'Mozambique',
    en: 'Mozambique',
    fr: 'Mozambique',
    code: 'MZ',
    code3: 'MOZ',
    phonePrefix: 258,
  },
  {
    es: 'Namibia',
    en: 'Namibia',
    fr: 'Namibie',
    code: 'NA',
    code3: 'NAM',
    phonePrefix: 264,
  },
  {
    es: 'Nauru',
    en: 'Nauru',
    fr: 'Nauru',
    code: 'NR',
    code3: 'NRU',
    phonePrefix: 674,
  },
  {
    es: 'Nepal',
    en: 'Nepal',
    fr: 'Népal',
    code: 'NP',
    code3: 'NPL',
    phonePrefix: 977,
  },
  {
    es: 'Nicaragua',
    en: 'Nicaragua',
    fr: 'Nicaragua',
    code: 'NI',
    code3: 'NIC',
    phonePrefix: 505,
  },
  {
    es: 'Niger',
    en: 'Niger',
    fr: 'Niger',
    code: 'NE',
    code3: 'NER',
    phonePrefix: 227,
  },
  {
    es: 'Nigeria',
    en: 'Nigeria',
    fr: 'Nigeria',
    code: 'NG',
    code3: 'NGA',
    phonePrefix: 234,
  },
  {
    es: 'Niue',
    en: 'Niue',
    fr: 'Niou',
    code: 'NU',
    code3: 'NIU',
    phonePrefix: 683,
  },
  {
    es: 'Noruega',
    en: 'Norway',
    fr: 'Norvège',
    code: 'NO',
    code3: 'NOR',
    phonePrefix: 47,
  },
  {
    es: 'Nueva Caledonia',
    en: 'New Caledonia',
    fr: 'Nouvelle-Calédonie',
    code: 'NC',
    code3: 'NCL',
    phonePrefix: 687,
  },
  {
    es: 'Nueva Zelanda',
    en: 'New Zealand',
    fr: 'Nouvelle-Zélande',
    code: 'NZ',
    code3: 'NZL',
    phonePrefix: 64,
  },
  {
    es: 'Omán',
    en: 'Oman',
    fr: 'Oman',
    code: 'OM',
    code3: 'OMN',
    phonePrefix: 968,
  },
  {
    es: 'Países Bajos',
    en: 'Netherlands',
    fr: 'Pays-Bas',
    code: 'NL',
    code3: 'NLD',
    phonePrefix: 31,
  },
  {
    es: 'Pakistán',
    en: 'Pakistan',
    fr: 'Pakistan',
    code: 'PK',
    code3: 'PAK',
    phonePrefix: 92,
  },
  {
    es: 'Palau',
    en: 'Palau',
    fr: 'Palau',
    code: 'PW',
    code3: 'PLW',
    phonePrefix: 680,
  },
  {
    es: 'Palestina',
    en: 'Palestine',
    fr: 'La Palestine',
    code: 'PS',
    code3: 'PSE',
    phonePrefix: 970,
  },
  {
    es: 'Panamá',
    en: 'Panama',
    fr: 'Panama',
    code: 'PA',
    code3: 'PAN',
    phonePrefix: 507,
  },
  {
    es: 'Papúa Nueva Guinea',
    en: 'Papua New Guinea',
    fr: 'Papouasie-Nouvelle-Guinée',
    code: 'PG',
    code3: 'PNG',
    phonePrefix: 675,
  },
  {
    es: 'Paraguay',
    en: 'Paraguay',
    fr: 'Paraguay',
    code: 'PY',
    code3: 'PRY',
    phonePrefix: 595,
  },
  {
    es: 'Perú',
    en: 'Peru',
    fr: 'Pérou',
    code: 'PE',
    code3: 'PER',
    phonePrefix: 51,
  },
  {
    es: 'Polinesia Francesa',
    en: 'French Polynesia',
    fr: 'Polynésie française',
    code: 'PF',
    code3: 'PYF',
    phonePrefix: 689,
  },
  {
    es: 'Polonia',
    en: 'Poland',
    fr: 'Pologne',
    code: 'PL',
    code3: 'POL',
    phonePrefix: 48,
  },
  {
    es: 'Portugal',
    en: 'Portugal',
    fr: 'Portugal',
    code: 'PT',
    code3: 'PRT',
    phonePrefix: 351,
  },
  {
    es: 'Puerto Rico',
    en: 'Puerto Rico',
    fr: 'Porto Rico',
    code: 'PR',
    code3: 'PRI',
    phonePrefix: 1,
  },
  {
    es: 'Qatar',
    en: 'Qatar',
    fr: 'Qatar',
    code: 'QA',
    code3: 'QAT',
    phonePrefix: 974,
  },
  {
    es: 'Reino Unido',
    en: 'United Kingdom',
    fr: 'Royaume-Uni',
    code: 'GB',
    code3: 'GBR',
    phonePrefix: 44,
  },
  {
    es: 'República Centroafricana',
    en: 'Central African Republic',
    fr: 'République Centrafricaine',
    code: 'CF',
    code3: 'CAF',
    phonePrefix: 236,
  },
  {
    es: 'República Checa',
    en: 'Czech Republic',
    fr: 'République Tchèque',
    code: 'CZ',
    code3: 'CZE',
    phonePrefix: 420,
  },
  {
    es: 'República Dominicana',
    en: 'Dominican Republic',
    fr: 'République Dominicaine',
    code: 'DO',
    code3: 'DOM',
    phonePrefix: '1 809',
  },
  {
    es: 'República de Sudán del Sur',
    en: 'South Sudan',
    fr: 'Soudan du Sud',
    code: 'SS',
    code3: 'SSD',
    phonePrefix: 211,
  },
  {
    es: 'Reunión',
    en: 'Réunion',
    fr: 'Réunion',
    code: 'RE',
    code3: 'REU',
    phonePrefix: 262,
  },
  {
    es: 'Ruanda',
    en: 'Rwanda',
    fr: 'Rwanda',
    code: 'RW',
    code3: 'RWA',
    phonePrefix: 250,
  },
  {
    es: 'Rumanía',
    en: 'Romania',
    fr: 'Roumanie',
    code: 'RO',
    code3: 'ROU',
    phonePrefix: 40,
  },
  {
    es: 'Rusia',
    en: 'Russia',
    fr: 'La Russie',
    code: 'RU',
    code3: 'RUS',
    phonePrefix: 7,
  },
  {
    es: 'Sahara Occidental',
    en: 'Western Sahara',
    fr: 'Sahara Occidental',
    code: 'EH',
    code3: 'ESH',
    phonePrefix: 212,
  },
  {
    es: 'Samoa',
    en: 'Samoa',
    fr: 'Samoa',
    code: 'WS',
    code3: 'WSM',
    phonePrefix: 685,
  },
  {
    es: 'Samoa Americana',
    en: 'American Samoa',
    fr: 'Les Samoa américaines',
    code: 'AS',
    code3: 'ASM',
    phonePrefix: '1 684',
  },
  {
    es: 'San Bartolomé',
    en: 'Saint Barthélemy',
    fr: 'Saint-Barthélemy',
    code: 'BL',
    code3: 'BLM',
    phonePrefix: 590,
  },
  {
    es: 'San Cristóbal y Nieves',
    en: 'Saint Kitts and Nevis',
    fr: 'Saint Kitts et Nevis',
    code: 'KN',
    code3: 'KNA',
    phonePrefix: '1 869',
  },
  {
    es: 'San Marino',
    en: 'San Marino',
    fr: 'San Marino',
    code: 'SM',
    code3: 'SMR',
    phonePrefix: 378,
  },
  {
    es: 'San Martín (Francia)',
    en: 'Saint Martin (French part)',
    fr: 'Saint-Martin (partie française)',
    code: 'MF',
    code3: 'MAF',
    phonePrefix: '1 599',
  },
  {
    es: 'San Pedro y Miquelón',
    en: 'Saint Pierre and Miquelon',
    fr: 'Saint-Pierre-et-Miquelon',
    code: 'PM',
    code3: 'SPM',
    phonePrefix: 508,
  },
  {
    es: 'San Vicente y las Granadinas',
    en: 'Saint Vincent and the Grenadines',
    fr: 'Saint-Vincent et Grenadines',
    code: 'VC',
    code3: 'VCT',
    phonePrefix: '1 784',
  },
  {
    es: 'Santa Elena',
    en: 'Ascensión y Tristán de Acuña',
    fr: 'Ascensión y Tristan de Acuña',
    code: 'SH',
    code3: 'SHN',
    phonePrefix: 290,
  },
  {
    es: 'Santa Lucía',
    en: 'Saint Lucia',
    fr: 'Sainte-Lucie',
    code: 'LC',
    code3: 'LCA',
    phonePrefix: '1 758',
  },
  {
    es: 'Santo Tomé y Príncipe',
    en: 'Sao Tome and Principe',
    fr: 'Sao Tomé et Principe',
    code: 'ST',
    code3: 'STP',
    phonePrefix: 239,
  },
  {
    es: 'Senegal',
    en: 'Senegal',
    fr: 'Sénégal',
    code: 'SN',
    code3: 'SEN',
    phonePrefix: 221,
  },
  {
    es: 'Serbia',
    en: 'Serbia',
    fr: 'Serbie',
    code: 'RS',
    code3: 'SRB',
    phonePrefix: 381,
  },
  {
    es: 'Seychelles',
    en: 'Seychelles',
    fr: 'Les Seychelles',
    code: 'SC',
    code3: 'SYC',
    phonePrefix: 248,
  },
  {
    es: 'Sierra Leona',
    en: 'Sierra Leone',
    fr: 'Sierra Leone',
    code: 'SL',
    code3: 'SLE',
    phonePrefix: 232,
  },
  {
    es: 'Singapur',
    en: 'Singapore',
    fr: 'Singapour',
    code: 'SG',
    code3: 'SGP',
    phonePrefix: 65,
  },
  {
    es: 'Sint Maarten',
    en: 'Sint Maarten',
    fr: 'Saint-Martin',
    code: 'SX',
    code3: 'SMX',
    phonePrefix: '1 721',
  },
  {
    es: 'Siria',
    en: 'Syria',
    fr: 'Syrie',
    code: 'SY',
    code3: 'SYR',
    phonePrefix: 963,
  },
  {
    es: 'Somalia',
    en: 'Somalia',
    fr: 'Somalie',
    code: 'SO',
    code3: 'SOM',
    phonePrefix: 252,
  },
  {
    es: 'Sri lanka',
    en: 'Sri Lanka',
    fr: 'Sri Lanka',
    code: 'LK',
    code3: 'LKA',
    phonePrefix: 94,
  },
  {
    es: 'Sudáfrica',
    en: 'South Africa',
    fr: 'Afrique du Sud',
    code: 'ZA',
    code3: 'ZAF',
    phonePrefix: 27,
  },
  {
    es: 'Sudán',
    en: 'Sudan',
    fr: 'Soudan',
    code: 'SD',
    code3: 'SDN',
    phonePrefix: 249,
  },
  {
    es: 'Suecia',
    en: 'Sweden',
    fr: 'Suède',
    code: 'SE',
    code3: 'SWE',
    phonePrefix: 46,
  },
  {
    es: 'Suiza',
    en: 'Switzerland',
    fr: 'Suisse',
    code: 'CH',
    code3: 'CHE',
    phonePrefix: 41,
  },
  {
    es: 'Surinám',
    en: 'Suriname',
    fr: 'Surinam',
    code: 'SR',
    code3: 'SUR',
    phonePrefix: 597,
  },
  {
    es: 'Svalbard y Jan Mayen',
    en: 'Svalbard and Jan Mayen',
    fr: 'Svalbard et Jan Mayen',
    code: 'SJ',
    code3: 'SJM',
    phonePrefix: 47,
  },
  {
    es: 'Swazilandia',
    en: 'Swaziland',
    fr: 'Swaziland',
    code: 'SZ',
    code3: 'SWZ',
    phonePrefix: 268,
  },
  {
    es: 'Tayikistán',
    en: 'Tajikistan',
    fr: 'Le Tadjikistan',
    code: 'TJ',
    code3: 'TJK',
    phonePrefix: 992,
  },
  {
    es: 'Tailandia',
    en: 'Thailand',
    fr: 'Thaïlande',
    code: 'TH',
    code3: 'THA',
    phonePrefix: 66,
  },
  {
    es: 'Taiwán',
    en: 'Taiwan',
    fr: 'Taiwan',
    code: 'TW',
    code3: 'TWN',
    phonePrefix: 886,
  },
  {
    es: 'Tanzania',
    en: 'Tanzania',
    fr: 'Tanzanie',
    code: 'TZ',
    code3: 'TZA',
    phonePrefix: 255,
  },
  {
    es: 'Territorio Británico del Océano Índico',
    en: 'British Indian Ocean Territory',
    fr: "Territoire britannique de l'océan Indien",
    code: 'IO',
    code3: 'IOT',
    phonePrefix: 246,
  },
  {
    es: 'Territorios Australes y Antárticas Franceses',
    en: 'French Southern Territories',
    fr: 'Terres australes françaises',
    code: 'TF',
    code3: 'ATF',
    phonePrefix: '',
  },
  {
    es: 'Timor Oriental',
    en: 'East Timor',
    fr: 'Timor-Oriental',
    code: 'TL',
    code3: 'TLS',
    phonePrefix: 670,
  },
  {
    es: 'Togo',
    en: 'Togo',
    fr: 'Togo',
    code: 'TG',
    code3: 'TGO',
    phonePrefix: 228,
  },
  {
    es: 'Tokelau',
    en: 'Tokelau',
    fr: 'Tokélaou',
    code: 'TK',
    code3: 'TKL',
    phonePrefix: 690,
  },
  {
    es: 'Tonga',
    en: 'Tonga',
    fr: 'Tonga',
    code: 'TO',
    code3: 'TON',
    phonePrefix: 676,
  },
  {
    es: 'Trinidad y Tobago',
    en: 'Trinidad and Tobago',
    fr: 'Trinidad et Tobago',
    code: 'TT',
    code3: 'TTO',
    phonePrefix: '1 868',
  },
  {
    es: 'Tunez',
    en: 'Tunisia',
    fr: 'Tunisie',
    code: 'TN',
    code3: 'TUN',
    phonePrefix: 216,
  },
  {
    es: 'Turkmenistán',
    en: 'Turkmenistan',
    fr: 'Le Turkménistan',
    code: 'TM',
    code3: 'TKM',
    phonePrefix: 993,
  },
  {
    es: 'Turquía',
    en: 'Turkey',
    fr: 'Turquie',
    code: 'TR',
    code3: 'TUR',
    phonePrefix: 90,
  },
  {
    es: 'Tuvalu',
    en: 'Tuvalu',
    fr: 'Tuvalu',
    code: 'TV',
    code3: 'TUV',
    phonePrefix: 688,
  },
  {
    es: 'Ucrania',
    en: 'Ukraine',
    fr: "L'Ukraine",
    code: 'UA',
    code3: 'UKR',
    phonePrefix: 380,
  },
  {
    es: 'Uganda',
    en: 'Uganda',
    fr: 'Ouganda',
    code: 'UG',
    code3: 'UGA',
    phonePrefix: 256,
  },
  {
    es: 'Uruguay',
    en: 'Uruguay',
    fr: 'Uruguay',
    code: 'UY',
    code3: 'URY',
    phonePrefix: 598,
  },
  {
    es: 'Uzbekistán',
    en: 'Uzbekistan',
    fr: "L'Ouzbékistan",
    code: 'UZ',
    code3: 'UZB',
    phonePrefix: 998,
  },
  {
    es: 'Vanuatu',
    en: 'Vanuatu',
    fr: 'Vanuatu',
    code: 'VU',
    code3: 'VUT',
    phonePrefix: 678,
  },
  {
    es: 'Venezuela',
    en: 'Venezuela',
    fr: 'Venezuela',
    code: 'VE',
    code3: 'VEN',
    phonePrefix: 58,
  },
  {
    es: 'Vietnam',
    en: 'Vietnam',
    fr: 'Vietnam',
    code: 'VN',
    code3: 'VNM',
    phonePrefix: 84,
  },
  {
    es: 'Wallis y Futuna',
    en: 'Wallis and Futuna',
    fr: 'Wallis et Futuna',
    code: 'WF',
    code3: 'WLF',
    phonePrefix: 681,
  },
  {
    es: 'Yemen',
    en: 'Yemen',
    fr: 'Yémen',
    code: 'YE',
    code3: 'YEM',
    phonePrefix: 967,
  },
  {
    es: 'Yibuti',
    en: 'Djibouti',
    fr: 'Djibouti',
    code: 'DJ',
    code3: 'DJI',
    phonePrefix: 253,
  },
  {
    es: 'Zambia',
    en: 'Zambia',
    fr: 'Zambie',
    code: 'ZM',
    code3: 'ZMB',
    phonePrefix: 260,
  },
  {
    es: 'Zimbabue',
    en: 'Zimbabwe',
    fr: 'Zimbabwe',
    code: 'ZW',
    code3: 'ZWE',
    phonePrefix: 263,
  },
];

export default countryList;
